### ISSUE TITLE
Option to convert pngs to lossy jpg or jxl?

### ISSUE THREAD

**Issue by arun54321** [Huluti/Curtail#113]

**Comment by nekohayo** [comment]
Very often I use PNGs as a "working format" to output from GIMP, then need to transcode to JPEG XL (issue #20) for the final archival or publication format. I don't know if this should be considered a duplicate of issue 20 or if this is specifically about being able to transcode from PNG to JXL instead of JPEG to JXL, but I do think that both should be supported, we should be able to transcode from anything to JXL.
