### ISSUE TITLE
No file conflict dialog if {filename}{suffix} already exists in the directory. Strange .bak file behavior.

### ISSUE THREAD

**Issue by akozlovskiy119** [Huluti/Curtail#54]
If a file named `{filename}{suffix}` already exists in the target directory, Curtail will replace it without any warning.

In addition to that, for PNG:
- In case of lossless compression, `{filename}{suffix}.bak` backup file will be created. If it already exists, it will be replaced by a new one;
- In case of lossy compression, no backup file will be created. Moreover, if it already exists, it will be completely removed.

Leaving aside the strange logic of the backup file creation, this could potentially cause loss of important user data. I expect Curtail to just show a file conflict dialog in such cases without any implicit backup files, as Nautilus file manager does, for example.

I am using Curtail 1.0.0 from Flathub.

**Comment by Huluti** [comment]
I'll review all that logic very soon based on your returns. I'll keep you posted.

**Comment by Huluti** [comment]
Thank you for your report. It's fixed in master by removing backup files and with adding a popup to ask to overwrite (or no) the image if the "final filename" already exists.

**Comment by andrenete** [comment]
Thank you, the situation is definitely better now with popups.

One nitpick is batch replacing. 'File conflict' dialog allows you to apply the selected action to all files. It can be helpful if you re-run compression for many files multiple times, for example, if you changed compression level or switched to lossy.
![Снимок экрана от 2021-02-25 23-08-04](https://user-images.githubusercontent.com/22382143/109210809-64965f00-77be-11eb-8f5c-5d79c10e8019.png)

---

`.bak` files remaining seems to come from `optipng` if `filename != new_filename` and if `new_filename` already exists. [Looks like it is still not fixed in `optipng`](https://sourceforge.net/p/optipng/bugs/74/), because `.bak` file remains even if `-backup` option is not specified.

In Curtail this combination appears in png lossless compression if suffix is not an empty string:
https://github.com/Huluti/Curtail/blob/8b288b5e680a2440f886dbef079d99ebc03eacb5/src/compressor.py#L103-L105

**Comment by Huluti** [comment]
You're right, these popups can be annoying... I'll try to add this "Apply this action to all files" popup before the next release. Thank's!

**Comment by Huluti** [comment]
I was not aware of the optipng bug. Can I do something about this?

**Comment by andrenete** [comment]
I don't think so, at least not in Curtail itself.

I just discovered this and left the info for future references.

**Comment by Huluti** [comment]
Ok right, you did well.

**Comment by Huluti** [comment]
> Thank you, the situation is definitely better now with popups.
> 
> One nitpick is batch replacing. 'File conflict' dialog allows you to apply the selected action to all files. It can be helpful if you re-run compression for many files multiple times, for example, if you changed compression level or switched to lossy.
> ![Снимок экрана от 2021-02-25 23-08-04](https://user-images.githubusercontent.com/22382143/109210809-64965f00-77be-11eb-8f5c-5d79c10e8019.png)
> 
> `.bak` files seems to come from `optipng` with `-clobber` option if `filename != new_filename` and if `new_filename` already exists. [Looks like it is still not fixed in `optipng`](https://sourceforge.net/p/optipng/bugs/74/), because `.bak` file remains, even if `-backup` option is not specified.
> 
> In Curtail this combination appears in png lossless compression if compression suffix is not an empty string:
> 
> https://github.com/Huluti/Curtail/blob/83b75f88ef142461b9bbf5a6b53340b5077c11c6/src/compressor.py#L103-L105
> 
> If `filename == new_filename` and no `-backup` specified, existing `.bak` file is removed. This is always the case in png lossy compression:
> 
> https://github.com/Huluti/Curtail/blob/83b75f88ef142461b9bbf5a6b53340b5077c11c6/src/compressor.py#L101-L102

@andrenete I have not many time now. Do you think this should be fixed before 1.1 or does the situation is better than before and we could work on that for 1.2? Thank's.

**Comment by axredneck** [comment]
> I was not aware of the optipng bug. Can I do something about this?

Switch to oxipng maybe?
