### ISSUE TITLE
Filesystem browser ignores symlinks

### ISSUE THREAD

**Issue by adrinux** [Huluti/Curtail#70]
If I drag and drop files from a different hard disk I get a 'path not valid' error.

If I try to use the file browser instead it opens at /home/myself  but ignores any symlinked folders. I have several of my home's subfolders symlinked to a secondary home on a raid array to free up space on my small nvme system drive. The array is mounted at /data in fstab.

Basically Curtail only sees files in my /home and won't follow symlinks.

Workaround: copy files to /home/myself for processing, then copy back.

Version: 1.1.0
Installed with: Flatpak (Flathub) - handled by manjaro's Pamac GUI installer
Running on: manjaro linux

(note: I had imcompressor installed via AUR and it seems whoever looks after the AUR package swapped in Curtail - slightly confusing at first, especially when the build failed. So I installed Curtail from Flatpak instead. Curtail is looking fantastic, I appreciate it's a WIP at the moment.)

**Comment by andrenete** [comment]
This is because Curtail Flatpak file access is [limited to home directory only](https://github.com/flathub/com.github.huluti.Curtail/blob/daec4f218cc125ede24c2c1e871c496e5d79fa79/com.github.huluti.Curtail.json#L11) by default.

If this is absolutely necessary, you can override file access permission to (almost) all files with
```bash
sudo flatpak override --filesystem=host com.github.huluti.Curtail
```

To reset to defaults use
```
sudo flatpak override --reset com.github.huluti.Curtail
```

Refer to [Flatpak documentation](https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access) for more info.

**Comment by adrinux** [comment]
This is the first time I've run up against the side of the sandbox!

Thanks. Works well with filesystem set to host.
